name: Continues Integration - PR Tag


on:
  pull_request:
    branches:
      - '*'


jobs:
  tag:
    name: Create a git tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create git tag
        uses: ./
        with:
          create: true
          pr-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read git tag
        id: read
        uses: ./
        with:
          read: true
          pr-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo read tag
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Read tag: ${{ steps.read.outputs.tag }}
