name: Continues Integration - Push Tag


on:
  push:
    tags:
      - '*'


jobs:
  tag:
    name: Read a git tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read git tag
        id: read
        uses: ./
        with:
          read: true
          ref: ${{ github.ref }}

      - name: Echo read tag
        run: |
          echo "tag = ${{ steps.read.outputs.tag }}"
          echo "is-final = ${{ steps.read.outputs.is-final }}"
          echo "sha = ${{ steps.read.outputs.sha }}"
          echo "pr-number = ${{ steps.read.outputs.pr-number }}"
